### ISSUE TITLE
Koszulka - projekt

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne_2016#11]

**Comment by dinerrr** [comment]
[koszulka2016.pdf](https://github.com/DrupalCampWroclaw/organizacyjne_2016/files/231338/koszulka2016.pdf)

**Comment by dinerrr** [comment]
![koszulka2016](https://cloud.githubusercontent.com/assets/8255035/14735201/e503a81e-086f-11e6-9db0-0c1235f815c8.png)

**Comment by dinerrr** [comment]
[koszulka drupalcamp.zip](https://github.com/DrupalCampWroclaw/organizacyjne_2016/files/231342/koszulka.drupalcamp.zip)

**Comment by grzegorzbartman** [comment]
Zrobione i zamówione
