### ISSUE TITLE
Kufel - projekt

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne_2016#14]

**Comment by robertkandzia** [comment]
**Propozycja 1**
![kufel_v1](https://cloud.githubusercontent.com/assets/8748753/14443082/51bcdccc-003d-11e6-9c0c-5f6f246f3de8.png)
![kufel_front_v1](https://cloud.githubusercontent.com/assets/8748753/14443081/51b777b4-003d-11e6-8278-06f2d067f011.png)

**Propozycja 2**
Jak powyżej, tylko zamiast krasnala to [logo Drupal 8](http://talks.matthewtift.com/osn/images/drupal-8-logo.png) w kolorze napisu "Wrocław".
